---
---


```{r}
url <- "/vsicurl/https://minio.carlboettiger.info/public-biodiversity/fire22_1.gdb"


library(sf)
library(dplyr)
#url <- "/vsis3/public-biodiversity/fire22_1.gdb"
st_layers(url)
fire <- st_read(url, "firep22_1")
fire |> filter(GIS_ACRES == max(GIS_ACRES))
august_complex <- fire |> filter(FIRE_NAME == "AUGUST COMPLEX") 

box <- august_complex |> st_transform(crs=4326) |> st_bbox()
```



```{r}
#remotes::install_github("OldLipe/rstac@b-0.9.1")
#remotes::install_github("appelmar/gdalcubes_R")
# remotes::install_github("r-spatial/stars")


library(rstac)
library(gdalcubes)
library(stars)
gdalcubes_options(parallel = TRUE)

matches <-
  stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "modis-15A2H-061",
              datetime = "2018-01-01/2023-07-01",
              bbox = c(box)) |>
  get_request() |>
  items_fetch() |>
  items_sign(sign_fn = sign_planetary_computer())
```


```{r}
cube <- gdalcubes::stac_image_collection(matches$features,
                                         asset_names = "Lai_500m",
                                         duration = "start")
v <- cube_view(srs = "EPSG:4326",
               extent = list(t0 = "2018-11-01", t1 = "2022-12-01",
                             left = box[1], right = box[3],
                             top = box[4], bottom = box[2]),
               nx = 200, ny = 200, dt= "P16D",
               aggregation = "mean", resampling = "near"
)
```


```{r}
d <- raster_cube(cube, v) |> gdalcubes::dimension_values()
d$t
```

```{r}
r2022 <- raster_cube(cube, v) |> 
  gdalcubes::slice_time("2022-08-08") |> 
  stars::st_as_stars()
```


```{r}
r2020 <- raster_cube(cube, v) |> 
  gdalcubes::slice_time("2020-09-03") |> 
  stars::st_as_stars()
```

```{r}
r2019 <- raster_cube(cube, v) |> gdalcubes::slice_time("2019-08-16") |> 
  stars::st_as_stars()
```

```{r}
r <- r2019[r2019 < 60]
library(tmap)
tm_shape(r) + 
  tm_raster(palette= viridisLite::mako(20), n=20, legend.show = FALSE) + 
  tm_shape(august_complex) + 
  tm_borders(col="white")
```

```{r}
r22 <- r2022[r2022 < 60]
library(tmap)
tm_shape(r22) + 
  tm_raster(palette= viridisLite::mako(20), n=20, legend.show = FALSE) + 
  tm_shape(august_complex) + 
  tm_borders(col="white")
```


```{r}
raster_cube(cube, v) |>
  animate(col = viridisLite::mako, zlim=c(0,60),
          key.pos = 1, save_as = "anim.gif", fps = 4)
```

## Other fire products

```{r}
# burned area monthly
burned <-
  stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "modis-64A1-061",
              datetime = "2018-01-01/2023-07-01",
              bbox = c(box)) |> get_request() |> items_fetch() |>
  items_sign(sign_fn = sign_planetary_computer())
```

```{r}
# Thermal Anomalies/Fire Daily modis-14A1-061
fire_daily <-
  stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "modis-14A1-061",
              datetime = "2018-01-01/2023-07-01",
              bbox = c(box)) |> get_request() |> items_fetch() |>
  items_sign(sign_fn = sign_planetary_computer())


```


## spongy moth defoliation? maybe?



Leaf-area index defoliation from Spongy moth

June-September 2016 vs 2017 Mass

```{r}
ma <- spData::us_states |> filter(grepl("Mass", NAME)) |> st_bbox()
moth <-
  stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "modis-15A2H-061",
              datetime = "2016-01-01/2023-07-01",
              bbox = c(ma)) |>
  get_request() |>
  items_fetch() |>
  items_sign(sign_fn = sign_planetary_computer())
```

```{r}
cube <- gdalcubes::stac_image_collection(moth$features,
                                         asset_names = "Lai_500m",
                                         duration = "start")
v2018 <- cube_view(srs = "EPSG:4326",
               extent = list(t0 = "2018-06-01", t1 = "2018-08-31",
                             left = ma[1], right = ma[3],
                             top = ma[4], bottom = ma[2]),
               nx = 200, ny = 200, dt= "P3M",
               aggregation = "mean", resampling = "near"
)
v2016 <- v2017 <- v2018
v2016$time$t0 = "2016-06-01"; v2016$time$t1 =  "2016-08-31"
v2017$time$t0 = "2017-06-01"; v2017$time$t1 =  "2017-08-31"

```


```{r}
r2016 <- raster_cube(cube, v2016) |> st_as_stars()
r <- terra::rast(r2016)
r <- r[r < 41]
mean(r)
#  plot(col = viridisLite::mako, zlim=c(0,60))
```

```{r}
r <- raster_cube(cube, v2017)  |> st_as_stars() |> terra::rast()
r <- r[r < 41]
mean(r)
```

```{r}
raster_cube(cube, v2017)  |> 
  plot(col = viridisLite::mako, zlim=c(0,60))
```


```{r}
raster_cube(cube, v2017) - raster_cube(cube, v2016) |> plot()
```




